### ISSUE TITLE
Loader Development

### ISSUE THREAD

**Issue by chrvadala** [nufaylr/react-svg-pan-zoom-loader#1]
Hi @nufaylr,
I published a full seed project. 
As next step could you integrate your loader implementation with this seed?

**Comment by nufaylr** [comment]
Hey @chrvadala , updated the yarn lock. and published into the npm registry. test and let me know. or we can close this issue. Many thanks

**Comment by nufaylr** [comment]
Also how about maybe we can close those issues in react-svg-pan-zoom and asked to refactor the code with react-svg-pan-zoom-loader module as clean solution. any thoughts ?

**Comment by chrvadala** [comment]
I closed the PR and the issue. I also added a link on the official documentation https://github.com/chrvadala/react-svg-pan-zoom#documentation. Users will be able to easily find this library.

**Comment by chrvadala** [comment]
Probably we can close also this issue. Thanks for your work!

**Comment by nufaylr** [comment]
Thank you @chrvadala . Oh! i didn't see new v3 coming 😄 this helped me to [React SVG Pan Zoom - Migrate from V2 to V3](https://github.com/chrvadala/react-svg-pan-zoom/blob/master/docs/migrate-from-v2-to-v3.md)
